apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-svc-opengame
subjects:
  - kind: ServiceAccount
    name: svc-opengame  # The ServiceAccount to bind
roleRef:
  kind: Role
  name: view  # Using OpenShift's built-in "view" role
  apiGroup: rbac.authorization.k8s.io

