apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: redis
          image: quay.io/redhattraining/hello-world-nginx
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "100m"
              memory: "200Mi"
          ports:
            - containerPort: 8080
              protocol: TCP
      dnsPolicy: ClusterFirst
      nodeSelector:
        base: alpha
      restartPolicy: Always
